### PR TITLE
Fix/make machine controller more resilient

### PR DESCRIPTION
**Pull request by kstiehl**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
* provider/anexia - make provisioning and de-provisioning more resilient
```

### CODE REVIEW

**Comment by kstiehl** [comment]
@LittleFox94  any idea on how to fix this rebasing issue

**Comment by LittleFox94** [comment]
I'll take a look

**Comment by LittleFox94** [comment]
Fixed your commits, some notes for future help:

* rebasing adds every commit, so fixing conflicts via added commits does not work
  - you have to change the conflicting commit not to conflict
  - I did this by `git rebase -i origin/main` and squashing your `adjust go.mod` commit into the other commit
* merging the main branch instead of rebasing on the main branch makes an additional merge commit we really don't need .. please rebase for such feature branches

This resulted in three commits being changed to a single one, but since I don't have your PGP key, you'll have to sign that commit again

**Comment by kstiehl** [comment]
Signature fixed
Thnx alot for fixing and explanation.

**Comment by LittleFox94** [comment]
merged upstream

**Pull request closed without merging**
